### ISSUE TITLE
Will the training data be open souced?

### ISSUE THREAD

**Issue by liming-ai** [ELLA-Diffusion/ELLA#4]

**Comment by melohux** [comment]
Currently, we are not planning to release our training data. Our method to generate the data can be found in the paper, and you can generate your own data using MLLM such as CogVLM :)

**Comment by liming-ai** [comment]
> Currently, we are not planning to release our training data. Our method to generate the data can be found in the paper, and you can generate your own data using MLLM such as CogVLM :)

Thanks for your reply. We do hope the data will be released for research.
